# Generated by Django 3.2.8 on 2021-11-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='courses/%Y/%m/%d/', verbose_name='Profile picture')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook profile URL')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter profile URL')),
                ('linkedin', models.URLField(blank=True, verbose_name='Linkedin profile URL')),
                ('youtube', models.URLField(blank=True, verbose_name='Youtube profile URL')),
            ],
        ),
    ]
